import keyMirror from "key-mirror";
let types = keyMirror({
  CHANGE_NAME: null,
  CHANGE_AGE: null,
  CHANGE_ASYNCDATA: null,

  CHANGE_COMPUTER_COLOR: null,
  CHANGE_COMPUTER_SIZE: null,
  CHANGE_COMPUTER_PRIZE: null,
  CHAGE_LEFTNAV: null,
  CHANGE_CHECKEDNAV: null,
  CHANGE_LEFTNAVSTATUS: null,
  SET_ENVLISTS: null,
  SAVE_LEFTNAVCHECKEDMETHOD: null,
});

const moduleConfig = [
  { label: "uve", value: "uve" },
  { label: "idx", value: "idx" },
  { label: "wax", value: "wax" },
  { label: "render", value: "render" },
  { label: "topfans", value: "topfans" },
  { label: "nofans", value: "nofans" },
];
const senceConfig = [
  { label: "主feed流", value: "mainfeed" },
  { label: "分组feed流", value: "groupfeed" },
  { label: "好友圈feed流", value: "friendfeed" },
  { label: "热门微博流", value: "hot_tweets_feed" },
  { label: "Profile微博流", value: "profile" },
  { label: "正文页", value: "single_page" },
  { label: "账号流", value: "account_feed" },
  { label: "热门话题", value: "hot_topic" },
  { label: "热门微博分类页", value: "hot_tweets_category" },
  { label: "视频后推荐流", value: "videofeed" },
  { label: "搜索流", value: "queryfeed" },
  { label: "weico主feed流", value: "weico_mainfeed" },
  { label: "找人页", value: "finding_friends" },
  { label: "找人页二级页", value: "finding_second" },
  { label: "他人态关系中心", value: "relation_center" },
  { label: "主人态关注列表", value: "my_following" },
  { label: "主人态粉丝列表", value: "my_follower" },
  { label: "粉丝列表二级页", value: "follower_second" },
  { label: "天气通-同城流", value: "weather_feed" },
  { label: "普搜流", value: "general_queryfeed" },
  { label: "文章页", value: "article" },
  { label: "评论流", value: "comments_list" },
  { label: "视频流", value: "video_tab" },
  { label: "发现页-视频流", value: "discover_video" },
  { label: "竖版视频流", value: "vertical_video" },
  { label: "故事流", value: "story_video" },
  { label: "图集流", value: "photo_feed" },
  { label: "节目流", value: "program_feed" },
  { label: "视频贴片流", value: "videopaster" },
  { label: "热门频道流", value: "hot_channel_feed" },
  { label: "极速版_关注流", value: "weibolite_mainfeed" },
  { label: "极速版_推荐流", value: "weibolite_hot" },
  { label: "问答流", value: "qa_feed" },
  { label: "问答banner", value: "qa_banner" },
  { label: "附近流", value: "nearby_feed" },
  { label: "新鲜事流", value: "freshnews_feed" },
  { label: "快应用_正文页", value: "wbfastapp_single_page" },
  { label: "新的好友页", value: "new_friends" },
  { label: "博主推荐", value: "blogger_recommend" },
  { label: "Profile页加关注后推", value: "follow_friends" },
  { label: "PC首页右侧", value: "pc_right_account" },
  { label: "国际版_主feed", value: "intl_mainfeed" },
  { label: "国际版_热门流", value: "intl_hot_tweets" },
  { label: "图集瀑布流", value: "photo_waterfall_feed" },
  { label: "超话", value: "supergroup" },
  { label: "正文页详情模块", value: "page_pic" },
  { label: "视频前贴", value: "prevideopaster" },
  { label: "热点(大)视窗", value: "hot_view" },
  { label: "绿洲发现流", value: "oasis_find_feed" },
  { label: "视频详情页", value: "video_detail_page" },
  { label: "直播前贴", value: "prelivepaster" },
  { label: "绿洲关注流", value: "oasis_main_feed" },
  { label: "发现页热点流", value: "discover_hotspot_feed" },
  { label: "拓展阅读流", value: "recommendation" },
];
const productsConfig = [
  { label: "超级粉丝通", value: "Sfst" },
  { label: "粉丝头条投非粉", value: "FanstopExtend" },
  { label: "WAX", value: "WAX" },
  { label: "涨粉", value: "AddFans" },
  { label: "视频角标", value: "VideoHighlight" },
  { label: "粉丝头条", value: "TopFans" },
  { label: "品牌热推", value: "Feedcpd" },
  { label: "视频翻版广告", value: "VideoBanner" },
  { label: "智能淘客", value: "AITao" },
  { label: "智能投放", value: "SmartD" },
  { label: "故事关注流顶部", value: "StoryTop" },
  { label: "视频三件套", value: "videoaccompaniedad" },
  { label: "直播伴随产品", value: "liveaccompaniedad" },
  { label: "品牌大视窗", value: "BrandView" },
];
const interfaceConfig = [
  { label: "trends/gateway", value: "trends_gateway" },
  { label: "render_v2/gateway", value: "render_v2_gateway" },
];
const optimizationObjectiveConfig = [
  { label: "86001002", value: "86001002" },
  { label: "86002002", value: "86002002" },
  { label: "86002001", value: "86002001" },
  { label: "86002003", value: "86002003" },
  { label: "86002004", value: "86002004" },
  { label: "86004001", value: "86004001" },
  { label: "86004002", value: "86004002" },
  { label: "86005001", value: "86005001" },
  { label: "86007001", value: "86007001" },
  { label: "86007002", value: "86007002" },
];
const promotionObjectiveConfig = [
  { label: "88030001", value: "88030001" },
  { label: "88030002", value: "88030002" },
  { label: "88030003", value: "88030003" },
  { label: "88030004", value: "88030004" },
  { label: "88030005", value: "88030005" },
  { label: "88030006", value: "88030006" },
];
export {
  moduleConfig,
  types,
  senceConfig,
  productsConfig,
  interfaceConfig,
  optimizationObjectiveConfig,
  promotionObjectiveConfig,
};
