import keyMirror from "key-mirror";
let types = keyMirror({
  CHANGE_NAME: null,
  CHANGE_AGE: null,
  CHANGE_ASYNCDATA: null,

  CHANGE_COMPUTER_COLOR: null,
  CHANGE_COMPUTER_SIZE: null,
  CHANGE_COMPUTER_PRIZE: null,
  CHAGE_LEFTNAV: null,
  CHANGE_CHECKEDNAV: null,
  CHANGE_LEFTNAVSTATUS: null,
  SET_ENVLISTS: null,
  SAVE_LEFTNAVCHECKEDMETHOD: null,
});

const moduleConfig = [
  { label: "uve", value: "uve" },
  { label: "idx", value: "idx" },
  { label: "wax", value: "wax" },
  { label: "render", value: "render" },
  { label: "topfans", value: "topfans" },
  { label: "nofans", value: "nofans" },
];
const senceConfig = [
  {label: '主feed流', value: 'mainfeed'},
  { label: "分组feed流", value: "groupfeed" },
  { label: "好友圈feed流", value: "friendfeed" },
  { label: "热门微博流", value: "hot_tweets_feed" },
  { label: "Profile微博流", value: "profile" },
  { label: "正文页", value: "single_page" },
  { label: "账号流", value: "account_feed" },
  { label: "热门话题", value: "hot_topic" },
  { label: "热门微博分类页", value: "hot_tweets_category" },
  { label: "视频后推荐流", value: "videofeed" },
  { label: "搜索流", value: "queryfeed" },
  { label: "weico主feed流", value: "weico_mainfeed" },
  { label: "找人页", value: "finding_friends" },
  { label: "找人页二级页", value: "finding_second" },
  { label: "他人态关系中心", value: "relation_center" },
  { label: "主人态关注列表", value: "my_following" },
  { label: "主人态粉丝列表", value: "my_follower" },
  { label: "粉丝列表二级页", value: "follower_second" },
  { label: "天气通-同城流", value: "weather_feed" },
  { label: "普搜流", value: "general_queryfeed" },
  { label: "文章页", value: "article" },
  { label: "评论流", value: "comments_list" },
  { label: "视频流", value: "video_tab" },
  { label: "发现页-视频流", value: "discover_video" },
  { label: "竖版视频流", value: "vertical_video" },
  { label: "故事流", value: "story_video" },
  { label: "图集流", value: "photo_feed" },
  { label: "节目流", value: "program_feed" },
  { label: "视频贴片流", value: "videopaster" },
  { label: "热门频道流", value: "hot_channel_feed" },
  { label: "极速版_关注流", value: "weibolite_mainfeed" },
  { label: "极速版_推荐流", value: "weibolite_hot" },
  { label: "问答流", value: "qa_feed" },
  { label: "问答banner", value: "qa_feed" },
  { label: "附近流", value: "nearby_feed" },
  { label: "新鲜事流", value: "freshnews_feed" },
  { label: "快应用_正文页", value: "wbfastapp_single_page" },
  { label: "新的好友页", value: "new_friends" },
  { label: "博主推荐", value: "blogger_recommend" },
  { label: "Profile页加关注后推", value: "follow_friends" },
  { label: "PC首页右侧", value: "pc_right_account" },
  { label: "国际版_主feed", value: "intl_mainfeed" },
  { label: "国际版_热门流", value: "intl_hot_tweets" },
  { label: "图集瀑布流", value: "photo_waterfall_feed" },
  { label: "超话", value: "supergroup" },
  { label: "正文页详情模块", value: "page_pic" },
  { label: "视频前贴", value: "prevideopaster" },
  { label: "热点(大)视窗", value: "hot_view" },
  { label: "绿洲发现流", value: "oasis_find_feed" },
  { label: "视频详情页", value: "video_detail_page" },
  { label: "直播前贴", value: "prelivepaster" },
  { label: "绿洲关注流", value: "oasis_main_feed" },
  { label: "发现页热点流", value: "discover_hotspot_feed" },
  { label: "拓展阅读流", value: "recommendation" }

];
const productsConfig = [
  {label: '超级粉丝通', value: 'Sfst'}
];
export { moduleConfig, types, senceConfig, productsConfig };
